apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mutating-webhook-selfsigned-issuer
  namespace: admission
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mutating-webhook-tls-secret
  namespace: admission
spec:
  duration: 8760h
  renewBefore: 8000h
  subject:
    organizations:
      - xiaolatiao.dev
  commonName: mutating-webhook.admission
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
  dnsNames:
    - mutating-webhook
    - mutating-webhook.admission
    - mutating-webhook.admission.svc
  ipAddresses:
    - 36.26.81.202
  issuerRef:
    kind: Issuer
    name: mutating-webhook-selfsigned-issuer
  secretName: mutating-webhook-tls-secret